"""empty message

Revision ID: 6bb55dc2595a
Revises: 32aae94f19d4
Create Date: 2016-09-15 23:50:02.738466

"""

# revision identifiers, used by Alembic.
revision = '6bb55dc2595a'
down_revision = '32aae94f19d4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roll_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=256), nullable=True),
    sa.Column('val', sa.String(length=256), nullable=True),
    sa.Column('user', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roll_model')
    ### end Alembic commands ###
