"""empty message

Revision ID: ded3d9b06c78
Revises: 66d55cc0a14b
Create Date: 2016-09-16 22:04:20.820065

"""

# revision identifiers, used by Alembic.
revision = 'ded3d9b06c78'
down_revision = '66d55cc0a14b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('highlight_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=256), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('highlight_model')
    ### end Alembic commands ###
